version: "3"

networks:
  nginx-proxy-manager:
    external: true
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1001
      - USER_GID=1001
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=##CHANGE_ME_IN_LINE_20_AND_40##
    restart: always
    networks:
      - nginx-proxy-manager
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "3000:3000"
#      - "6080:22"
    depends_on:
      - gitea-db
  gitea-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=##CHANGE_ME_TO_ANOTHER_STRONG_PASSWORD##
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=##CHANGE_ME_IN_LINE_20_AND_40##
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql